export const COMMON = {
  ALERT: '[data-qa=alert]',
  ALERT_CLOSE_BTN: '[data-qa=alert-close-btn]',
  WARN_MODAL_CANCEL_BTN: '[data-bb-handler=cancel]',
  WARN_MODAL_CONFIRM_BTN: '[data-bb-handler=confirm]',
}

export const LOGIN_LOCATORS = {
  USERNAME: '[data-qa=username-input]',
  PASSWORD: '[data-qa=password-input]',
  LOGIN_FORM: '[data-qa=login-form]',
}

export const CAMPAIGN_CREATION = {
  NEW_CAMPAIGN_BTN: '[data-qa=campaign-creation-btn]',
  CAMPAIGN_PLATFORM_TYPE: (id) => `[data-qa=platform-type-id-${id}]`,
  CAMPAIGN_CREATIVE_TYPE: '[data-qa=campaign-creative-type-select]',
  CAMPAIGN_CHANNEL_TYPE: '[data-qa=campaign-channel-type-select]',
  CAMPAIGN_NAME_INPUT: '[data-qa=campaign-name-input]',
  CAMPAIGN_GOAL: (id) => `[data-qa=campaign-goal-type-id-${id}]`,
  CAMPAIGN_PRIMARY_GOALS: (value) => `[data-qa=primary-goal-id-${value}]`,
  CAMPAIGN_PRIMARY_GOAL_AMOUNT: (value) => `[data-qa='primary-goal-id-${value}']`,
  CAMPAIGN_PRIMARY_GOALS_INPUT: '[data-qa=primary-goal-input]',
  CAMPAIGN_PRIMARY_GOALS_SAVE_BTN: '[data-qa=primary-goal-save-btn]',
  IMPRESSION_CAPPING_SECTION: '[data-qa=ac-capping]',
  DEFAULT_COUNTRY_IMPRESSION_CAPPING_CHECK: '[data-qa=default-country-impression-capping-check]',
  IMPRESSION_CAPPING_IMPRESSION_INPUT: '[data-qa=impression-capping-impression-input-0]',
  IMPRESSION_CAPPING_CLICKS_INPUT: '[data-qa=impression-capping-click-input-0]',
  CAPPING_AMOUNT_INPUT: '[data-qa=impression-capping-amount-input-0]',
  CAPPING_TIME_TYPE_SELECT: '[data-qa=impression-capping-time-type-select-0]',
  CAMPAIGN_PRIMARY_GOALS_REMOVE_BTN: '[data-qa=primary-goal-remove-btn]',
  CAMPAIGN_DATE_RANGE_FIELD: '[data-qa=date-range-field-input]',
  CAMPAIGN_DATE_PICKER_QUICKLINK: (quickLink) => `[data-qa*=date-picker-quicklink-${quickLink}]`,
  CAMPAIGN_DATE_PICKER_APPLY_BTN: '[data-qa=datepicker-apply-btn]',
  CAMPAIGN_DATE_PICKER_CANCEL_BTN: '[data-qa=datepicker-cancel-btn]',
  CAMPAIGN_BID_INPUT: '[data-qa=bid-currency-input]',
  CAMPAIGN_DAILY_BUDGET: '[data-qa=budget-daily-currency-input]',
  CAMPAIGN_TOTAL_BUDGET: '[data-qa=budget-total-currency-input]',
  NONE_BUDGET_PACING: '[data-qa=budget-pacing-none-radio]',
  EVEN_BUDGET_PACING: '[data-qa=budget-pacing-even-radio]',
  CAMPAIGN_COUNTRY_SELECT: 'select#country',
  CAMPAIGN_DEALS_AND_PACKAGE_SECTION: '[data-qa=deals-and-packages]',
  CAMPAIGN_PLATFORMS_TELCO_AND_DEVICES_SECTION: '[data-qa=platforms-telco-devices]',
  CAMPAIGN_DEVICE_BRAND_SECTION: '[data-qa=device-brand]',
  CAMPAIGN_DEVICE_MODEL_SECTION: '[data-qa=device-models]',
  CAMPAIGN_PACKAGE_BOX: '[data-qa=packages-box]',
  CAMPAIGN_PACKAGE_CHECK: (id) => `[data-qa=package-id-${id}]`,
  CAMPAIGN_PACKAGE_INCLUDE_CHECK: (typeId, packageId) => `[data-qa*=js-package-type-id-${typeId}-${packageId}]`,
  CAMPAIGN_PACKAGE_TYPE_INPUT: (typeId, packageId) => `input[name='package_type_percentage[${packageId}][${typeId}]']`,
  CAMPAIGN_CLICK_URL_SELECT: 'select#click_url_type',
  CAMPAIGN_LANDING_PAGE: '[data-qa=campaign-click-url-input]',
  CAMPAIGN_AD_DOMAIN_SELECT: '[data-qa=ad-domain-select]',
  CAMPAIGN_AD_DOMAIN_SELECT_OPTION: '[data-qa="ad-domain-select"] option',
  CAMPAIGN_AD_DOMAIN_ERROR: '#ad_domain-error',
  CAMPAIGN_HTTP_STATUS_LOADING: '[data-qa=http-status-loading]',
  CAMPAIGN_HTTP_STATUS_OK: '[data-qa=http-status-ok]',
  CAMPAIGN_HTTP_STATUS_ERROR: '[data-qa=http-status-error]',
  CAMPAIGN_CREATIVE_SET: 'select#selected_creative_sets',
  CAMPAIGN_PUBLISH_BTN: '[data-qa=publish-campaign-btn]',
  CAMPAIGN_DRAFT_BTN: '[data-qa=draft-campaign-btn]',
  CAMPAIGN_CANCEL_BTN: '[data-qa=cancel-campaign-btn]',
  CAMPAIGN_APPROVE_LINK: '[data-qa=campaign-approve-link]',
  CAMPAIGN_CREATIVE_INVALID_LINK: '[data-qa=invalid-url-alert]',
  CAMPAIGN_ITEM_ACTION: (id) => `[data-qa=item-action-${id}]`,
  CAMPAIGN_DELETE: (id) => `[data-qa=item-action-Delete-${id}]`,
  CAMPAIGN_DEVICE_OS_SELECT: 'select[data-qa=oses]',
  CAMPAIGN_DEVICE_BROWSERS_SELECT: 'select[data-qa=device-browsers-select]',
  CAMPAIGN_DEVICE_COST_SELECT: 'select[data-qa=device-cost-select]',
  CAMPAIGN_DEVICE_BRAND_SELECT: 'select[data-qa=device-brand-select]',
  CAMPAIGN_DEVICE_MODEL_SELECT: 'select[data-qa=device-model-select]',
  CAMPAIGN_BRAND_SAFETY_EXCLUDE_APP_SITES_CATEGORIES: '[data-target=\\#brandsafety-data-target]',
  CAMPAIGN_BRAND_SAFETY_EXCLUDE_APP_SITES_CATEGORIES_TOPICS: (id) => `[data-qa=siteCategoriesBrandSafety-id-${id}]`,
  CAMPAIGN_BRAND_SAFETY_EXCLUDE_APP_SITES_CATEGORIES_CHECK: (topic_id, cat_id) =>
    `[data-qa=siteCategoriesBrandSafetyChild-${topic_id}-id-${cat_id}]`,
  CAMPAIGN_BRAND_SAFETY_SELECT: 'select[data-qa=brand-safety-select]',
  CAMPAIGN_CONTEXTUAL_TARGETING_SELECT: 'select[data-qa=contextual-targeting-select]',
  MOBILE_OPERATORS_SELECT: 'select[data-qa=operators-container]',
  AD_PLACEMENT_TYPE_CHECK: (id) => `[data-qa=ad-placement-type-${id}]`,
  IP_ADDRESSES_TEXTAREA: '[data-qa=ip-ranges-box]',
  IP_ADDRESSES_INCLUDE_INPUT: '[data-qa=ip-ranges-include-radio]',
  IP_ADDRESSES_EXCLUDE_INPUT: '[data-qa=ip-ranges-exclude-radio]',
  DEVICE_TYPE_SELECT: 'select[data-qa=device-type-select]',
  DEVICE_BRAND_INCLUDE_INPUT: '[data-qa=device-brands-include-radio]',
  DEVICE_BRAND_EXCLUDE_INPUT: '[data-qa=device-brands-exclude-radio]',
  DEVICE_MODEL_INCLUDE_INPUT: '[data-qa=device-models-include-radio]',
  DEVICE_MODEL_EXCLUDE_INPUT: '[data-qa=device-models-exclude-radio]',
  SIM_AMOUNT_CHECK: (id) => `[data-qa=sim-amount-check-${id}]`,
  DEVICE_CONNECTION_CHECK: (id) => `[data-qa=device-connection-check-${id}]`,
  DEVICE_CONN_EXCLUDE_INPUT: (id) => `[data-qa=device-con-supp-exclude-radio-${id}]`,
  DEVICE_CONN_ONLY_INPUT: (id) => `[data-qa=device-con-supp-only-radio-${id}]`,
  NETWORK_CONNECTION_CHECK: (id) => `[data-qa=network-connection-check-${id}]`,
  NETWORK_CONN_EXCLUDE_INPUT: (id) => `[data-qa=network-connnection-exclude-radio-${id}]`,
  NETWORK_CONN_ONLY_INPUT: (id) => `[data-qa=network-connnection-only-radio-${id}]`,
  MULTIPLE_OPERATOR_SIM_CARD_SELECT: 'select[data-qa=multiple-operator-sim-card-select]',
  MOBILE_DATA_CONSUMPTION_SELECT: 'select[data-qa=mobile-data-consumption-select]',
  OPERATOR_CHURN_SELECT: 'select[data-qa=operator-churn-select]',
  AD_EXCHANGE_CHECK: (id) => `[data-qa=ad-exchange-check-${id}]`,
  AD_PLACEMENT_POSITION_CHECK: (id) => `[data-qa=ad-placement-positions-check-${id}]`,
  PRIVATE_MARKETPLACE_SELECT: 'select[data-qa=private-marketplace-select]',
  CLICK_URL_TYPE_SELECT: 'select[data-qa=click-url-type-select]',
  PRIVATE_MARKETPLACE_INCLUDE_INPUT: '[data-qa=private-marketplace-include-radio]',
  PRIVATE_MARKETPLACE_ONLY_INPUT: '[data-qa=private-marketplace-only-radio]',
  CAMPAIGN_CREATIVE_TOGGLE_BTN: (id) => `[data-qa=creative-toggle-btn-${id}]`,
  CAMPAIGN_CREATIVE_BID_CPM: (id) => `[name="campaign_creative[${id}][bid_currency]"]`,
  CAMPAIGN_CREATIVE_CLICK_URL: (id) => `[href="#click-url-${id}"]`,
  CAMPAIGN_CREATIVE_CLICK_URL_INPUT: (id) => `[name="campaign_creative[${id}][click_url]"]`,
}

export const CAMPAIGN_APPROVE = {
  CAMPAIGN_APPROVE_LINK: '[data-qa=campaign-approve-link]',
  DEMOGRAPHIC_NO_SYNC_CHECK: '[data-qa=demographic-no-sync-check]',
  ADVERTISER_NAME_SELECT: 'select#adv-name',
  SEARCH_INPUT_FIELD: 'input#filter_name',
  ADVERTISEMENT_CATEGORIES: '[data-qa=advertisement-categories-select]',
  INCLUDE_ADVERTISEMENT_CATEGORIES: '[data-qa=include-new-categories-check]',
  APP_SITE_CATEGORY: '[data-qa=js-app-site-categories-select]',
  ALLOW_MULTIPLE_BIDS: '[data-qa=multiple-bids-per-user-check]',
  EXCHANGE_CHECK_ALL_BTN: '[data-qa=exchange-check-all-btn]',
  EXCHANGE_UNCHECK_ALL_BTN: '[data-qa=exchange-uncheck-all-btn]',
  BIDSWITCH_CHECK_ALL_BTN: '[data-qa=bidswitch-check-all-btn]',
  BIDSWITCH_UNCHECK_ALL_BTN: '[data-qa=bidswitch-uncheck-all-btn]',
  EXCHANGE: (id) => `[data-qa=exchange-id-${id}]`,
  CAMPAIGN_APPROVE_BTN: '[data-qa=campaign-approve-btn]',
  MASS_CAMPAIGN_APPROVE_WARNING_IGNORE_BTN: 'button.btn-danger',
  MASS_CAMPAIGN_APPROVE_BTN: '[data-qa=approve-btn]',
  CAMPAIGN_LIST_TABLE_ROW: 'table[data-qa="campaign-list-table"] tbody tr',
  CAMPAIGN_UNCHECK_DOMAIN_SPOOFERS: '[data-qa="Exclude Domain spoofers"]',
  APP_SITE_CATEGORY_INCLUDE_RADIO_INPUT: '[data-qa="app-site-category-include-radio"]',
  APP_SITE_CATEGORY_EXCLUDE_RADIO_INPUT: '[data-qa="app-site-category-exclude-radio"]',
  FILTER_BY_CAMPAIGN_STATUS_SELECT: '[data-qa="campaign-status-filter-select"]',
}

export const CAMPAIGN_MASS_EDIT = {
  MASS_NAME_INPUT: '[data-qa=form-control-mass-name-apply-input]',
  MASS_BID_INPUT: '[data-qa=mass-1-bid_currency-input]',
  MASS_DAILY_BUDGET_INPUT: '[data-qa=mass-1-budget_daily_currency-input]',
  MASS_TOTAL_BUDGET_INPUT: '[data-qa=mass-1-budget_total_currency-input]',
  MASS_LANDING_INPUT: '[data-qa=mass-landing-input--1]',
  MASS_AD_DOMAIN_ARROW: '[data-qa="mass-ad-domain-select--1"] ~ span.select2 b',
  MASS_AD_DOMAIN_INPUT: 'input.select2-search__field',
  MASS_PACKAGE_BTN: '[data-qa=mass-package-selection-btn--1]',
  MASS_PACKAGE_UNCHECK_ALL_BTN: '[data-qa=package-uncheck-all-btn]',
  MASS_PACKAGE_OK_BTN: 'button.data-qa-ok-btn',
  MASS_SAVE_BTN: '[data-qa=mass-edit-submit-btn]',
  PACKAGE: (id) => `[data-qa=package-input-${id}]`,
  PACKAGE_TYPE: (id) => `input#js-package-43286-type-id--${id}`,
}

export const AD_HTML = {
  STATIC_AD_IMG: 'a',
}

export const CAMPAIGN_VIEW = {
  CAMPAIGN_IMPRESSIONS: '[data-qa=campaign-view-impressions]',
  CAMPAIGN_CLICKS: '[data-qa=campaign-view-clicks]',
}

export const SIDE_MENU_BAR = {
  CREATIVE_SET: "[data-qa='Creative sets']",
}

export const CAMPAIGN_LIST = {
  SEARCH_INPUT: "[data-qa='search-filter-input']",
  CAMPAIGN_SINGLE_DUPLICATE: (id) => `[data-qa="item-action-Duplicate campaign-${id}"]`,
}

export const CREATIVE_CREATION = {
  ADD_CREATIVE_SET_BTN: '[data-qa=add-creative-set-btn]',
  CREATIVE_SET_TITLE_INPUT: '[data-qa=js-creativeset-title-input]',
  CREATIVE_FORMAT_SELECT: '[data-qa=creative-format-select]',
  CREATIVE_SET_SAVE_BTN: '[data-qa=creative-set-save-btn]',
  CREATIVE_SUBTYPE_SELECT: '[data-qa=js-creative-subtype-select]',
  ADD_CREATIVE_CONTINUE_BTN: '[data-qa=add-creative-continue-btn]',
  ENABLE_SAFEFRAME_CHECK: '[data-qa=enable-safeframe-check]',
  UPLOAD_BANNER_INPUT: 'input.uppy-FileInput-input',
  VIDEO_DESCRIPTION_TEXTAREA: '[data-qa=js-creative-asset-video-description-textarea]',
  CREATIVE_SUBMIT_BTN: '[data-qa=submit-creative-btn]',
  CREATIVE_SET_SEARCH_INPUT: '[data-qa=creative-set-search-filter-input]',
  CREATIVE_SET_TABLE_ROW: 'table[id="creative-sets-table"] tbody tr td a',
  CREATIVE_TABLE_ROW: 'table[id="creatives-table"] tbody tr td a',
  CREATIVE_SET_TITLE_ROW: (id) => `[data-qa=creative-set-title-${id}]`,
  CREATIVE_ITEM_ACTION: (id) => `[data-qa=item-action-${id}]`,
  CREATIVE_DELETE: (id) => `[data-qa=item-action-Delete-${id}]`,
}
